name: CI

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Verify Vial UID is unique
      run: python3 util/ci_vial_verify_uid.py

    - name: Compile Vial keyboards
      run: |
        make git-submodule
        python3 util/ci_compile_vial_keyboards.py
